<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9e669814-de43-400e-b1ce-cc8b9c1e9adb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TaskManagement.ReminderService.Tests\**" />
    <Content Remove="TaskManagement.ReminderService.Tests\**" />
    <EmbeddedResource Remove="TaskManagement.ReminderService.Tests\**" />
    <None Remove="TaskManagement.ReminderService.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

</Project>
